# Generated by Django 4.1.4 on 2022-12-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Description')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
