"""delete contact description

Revision ID: 53c00516b68f
Revises: a7dda3219fcd
Create Date: 2022-12-09 12:25:33.027826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c00516b68f'
down_revision = 'a7dda3219fcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('description', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
